### PR TITLE
CMake: add cmake installation; add SIMPLEINI_USE_SYSTEM_GTEST option

### PR DESCRIPTION
**Pull request by topazus**
The PR does the folllowing things, which will help for packaging in Linux when using CMake:

- Generate the CMake config, version and target files, and install them
- Installation of header file
- Add SIMPLEINI_USE_SYSTEM_GTEST option to choose to use system gtest dependency or not.

### CODE REVIEW

**Comment by brofield** [comment]
I'm happy that SimpleIni is getting some love from the CMake users, but it concerns me that none of these contributions are tested in any way by the build or test harness. What do you think about contributing a change so that build and execute of the test harness uses CMake?

**Comment by dacap** [comment]
Just making some comments in this PR as I was asked for:

1. This PR has two different changes (probably would be better to have two commits)
2. I agree about `SIMPLEINI_USE_SYSTEM_GTEST`, it's a good option for Linux platforms
3. I'm not used to all the `GNUInstallDirs` options, so I cannot make a valid point about them but it looks like something needed to do a "make install"

It would be nice to include some alternative GitHub workflow to test the cmake toolchain.

**Comment by topazus** [comment]
> 1. This PR has two different changes (probably would be better to have two commits)

Thanks for your advice, I will split it into two commits.

> * I agree about `SIMPLEINI_USE_SYSTEM_GTEST`, it's a good option for Linux platforms
> * I'm not used to all the `GNUInstallDirs` options, so I cannot make a valid point about them but it looks like something needed to do a "make install"

Yes, use system gtest and use `GNUInstallDirs` will facilitate to help with Linux packaging. Btw, I am trying to make simpleini package into Fedora official repository. By applying this patch, it seems fine when building RPM package. see build log: https://kojipkgs.fedoraproject.org//work/tasks/1336/110961336/build.log

**Comment by brofield** [comment]
Thank you for your contribution.

**Comment by brofield** [comment]
Looking more into the cmake build harness, and I'm wondering why was the SIMPLEINI_USE_SYSTEM_GTEST option necessary? Wouldn't adding the package to the FetchContent_Declare statement be best? i.e. use the installed package and if not available then build it outselves:

https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#guide:Using%20Dependencies%20Guide

include(FetchContent)
FetchContent_Declare(
	googletest
	DOWNLOAD_EXTRACT_TIMESTAMP ON
	URL https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip
	URL_HASH SHA1=0ac421f2ec11af38b0fff0f1992184032731a8bc
	FIND_PACKAGE_ARGS NAMES GTest
	)
FetchContent_MakeAvailable(googletest)

**Pull request merged**
